### PR TITLE
MPI Variants

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by dalcinl** [comment]
So, @minrk , I did not expect the Open MPI builds to succeed. Part of the problem is on PETSc makefiles and the way the handle errors. But anyway, conda managed to install both MPICH and Open MPI in the build environment? Should we worry about this? Or maybe just a consequence of PETSc dependencies not yet properly built to support MPI variants?

**Comment by minrk** [comment]
> maybe just a consequence of PETSc dependencies not yet properly built to support MPI variants?

I think this is it. One or more dependencies requires mpich directly, so both mpich and openmpi are requested. This *will* result in a failure to install, but doesn't yet. If you look at the output, you can see that it's pulling in mpich-3.2_5, the last build before mpich began depending on the new metapackage.

For mutual exclusivity, the mpi metapackage needs old builds of mpich and openmpi to be marked as broken so they don't get considered as valid resolutions to conflicts in the solver. This is the next task [in the metapackage PR](https://github.com/conda-forge/staged-recipes/pull/1501) and needs to be done by a conda-forge admin (@ocefpaf?). openmpi-3.0.0-0 needs to be marked as broken (I think we can leave openmpi 2.x alone) and all mpich builds 3.2-5 and older must be marked as broken.

**Comment by minrk** [comment]
Yup, openmpi build failed with the desired error:

```
Can't build /recipe_root due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - hypre 2.11.2 -> mpich -> mpi 1.0 mpich
  - openmpi 3.0.* -> mpi 1.0 openmpi
Use "conda info <package>" to see the dependencies for each package.
```

So hypre needs to be updated to support variants. I suspect several dependencies need the same treatment.

**Comment by dalcinl** [comment]
Closed in favor of #34.

**Pull request closed without merging**
