### PR TITLE
Update openblas pin

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by dalcinl** [comment]
@minrk We are pinning openblas at micro versions. Do we really such granularity?

**Comment by minrk** [comment]
>  Do we really such granularity?

Yes. When petsc links openblas, it links specifically to the x.y.z filename. So if the openblas patch version changes, petsc will fail to load because the path is wrong, even if the updated library is ABI-compatible.

This is true in general when linking library dependencies. Libraries must be pinned to the level that guarantees:

- ABI compatible (typically minor revisions satisfy this)
- load name is the same (install_name on mac, often overlooked, see https://github.com/conda-forge/suitesparse-feedstock/pull/23)

For petsc:

```
$ otool -L ~/conda/envs/test-openblas/lib/libpetsc.dylib
~/conda/envs/test-openblas/lib/libpetsc.dylib:
	@rpath/libpetsc.3.8.dylib (compatibility version 3.8.0, current version 3.8.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	@rpath/libumfpack.5.7.6.dylib (compatibility version 5.0.0, current version 5.7.6)
	@rpath/libklu.1.3.8.dylib (compatibility version 1.0.0, current version 1.3.8)
	@rpath/libcholmod.3.0.11.dylib (compatibility version 3.0.0, current version 3.0.11)
	@rpath/libbtf.1.2.6.dylib (compatibility version 1.0.0, current version 1.2.6)
	@rpath/libccolamd.2.9.6.dylib (compatibility version 2.0.0, current version 2.9.6)
	@rpath/libcolamd.2.9.6.dylib (compatibility version 2.0.0, current version 2.9.6)
	@rpath/libcamd.2.4.6.dylib (compatibility version 2.0.0, current version 2.4.6)
	@rpath/libamd.2.4.6.dylib (compatibility version 2.0.0, current version 2.4.6)
	@rpath/libsuitesparseconfig.4.5.4.dylib (compatibility version 4.0.0, current version 4.5.4)
	@rpath/libopenblasp-r0.2.19.dylib (compatibility version 0.0.0, current version 0.0.0) <- openblas-0.2.20 won't be loaded
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	@rpath/libmpi.12.dylib (compatibility version 14.0.0, current version 14.0.0)
	@rpath/libpmpi.12.dylib (compatibility version 14.0.0, current version 14.0.0)

```

It's possible that this can be relaxed starting with 0.2.20 thanks to https://github.com/conda-forge/openblas-feedstock/pull/32

**Comment by minrk** [comment]
This will need to wait until https://github.com/conda-forge/suitesparse-feedstock/pull/26 lands

**Comment by dalcinl** [comment]
@jschueller Please manually re-trigger the build in Circle-CI.

**Comment by jschueller** [comment]
@dalcinl I dont have rights

**Pull request closed without merging**
