### PR TITLE
Build with superlu

### PR DESCRIPTION
**Pull request by martinRenou**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martinRenou** [comment]
@conda-forge-admin, please rerender

**Comment by dalcinl** [comment]
@conda-forge-admin, please restart ci

**Comment by martinRenou** [comment]
@dalcinl Do you know why it does not build on OSX with openmpi? I did some research on the error message but I'm clueless...

**Comment by martinRenou** [comment]
I don't understand why simply adding superlu can break those tests.

**Comment by dalcinl** [comment]
@martinRenou I'm clueless. Can you temporarily remove the `--with-superlu` configure flag and try again? My guess is that this is not really related to the extra package, but that something is already broken.

**Comment by martinRenou** [comment]
I remember trying without it and it actually built. But I can try again if you want

**Comment by dalcinl** [comment]
> I remember trying without it and it actually built. But I can try again if you want

Please do, that way we can compare build dependencies one by one and figure out if something is broken (maybe the superlu package needs a rebuild!).

**Comment by martinRenou** [comment]
So it passes when not built with superlu. I'll try to rebuild superlu first.

**Comment by martinRenou** [comment]
I did rebuild superlu, trying again now :)

**Comment by martinRenou** [comment]
And it works! @dalcinl

**Comment by dalcinl** [comment]
@martinRenou There is something that is confusing me. In your commit 2781468, you mention SuperLU_DIST (in the commit message). However, you are not passing `--with-superlu_dist=1` to configure, nor are you adding a dependency on the `superlu_dist` package to the recipe. Is that what you really want? I would argue that PETSc users would expect both SuperLU and SuperLU_DIST being available rather than just the first.

**Comment by martinRenou** [comment]
Right, my first intention was to add superlu and superlu_dist in one single PR. But superlu_dist itself does not build. I am currently trying to fix superlu_dist 's build. I can rename my commit here and will do a separate PR building petsc with superlu_dist when it works, what do you think?

**Comment by martinRenou** [comment]
For reference: https://github.com/conda-forge/openmp-feedstock/pull/28 https://github.com/conda-forge/superlu_dist-feedstock/pull/4. My first idea was to add a variant of SuperLU-dist with openmpi but I realized master does not build. That's what I am trying to fix right now.

**Pull request merged**
