### PR TITLE
Manual Migration to GCC 9.3.0 

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by dalcinl** [comment]
@conda-forge-admin restart ci

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by jan-janssen** [comment]
@dalcinl I assume this finally works as I noticed one dependency was missing which should be fixed now. In case it does, we should most likely also backport the migration to 3.13 as the migration is still in progress https://conda-forge.org/status/#petsc313

**Comment by jan-janssen** [comment]
The drone tests finished successful but the travis tests were broken - but those worked before - so I just try it again.

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by beckermr** [comment]
@conda-forge-admin restart ci

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by dalcinl** [comment]
@beckermr Some builds failed after the merge.

I could restart the Azure ones, but not the Travis ones (got *Oh no! An error occurred. The job could not be restarted.*)

**Comment by dalcinl** [comment]
It seems the Travis issue was a temporary one, I managed to restart the failing jobs.

**Comment by dalcinl** [comment]
After many manual restarts of the failing jobs on Travis, now all the builds are OK.

**Comment by jan-janssen** [comment]
@dalcinl Thanks a lot, I guess we now have to figure out if we do a back port of petsc 3.13 to gcc 9.3.0. I started to look into the last missing migrations to 3.13:
* https://github.com/conda-forge/proteus-feedstock/pull/27 - should be fixed
* https://github.com/conda-forge/fenics-feedstock/pull/109 - is not working ... 

Once these are done, then the petsc 3.14 migration is triggered, if that is the case then I guess we do not need the back port of petsc 3.13 to gcc 9.3.0

**Comment by jan-janssen** [comment]
Ok, I just noticed that I still need petsc 3.13 for https://github.com/conda-forge/damask-feedstock which is the main motivation for me to trigger all the gcc 9.3.0 migrations. Can you create a new branch for petsc 3.13 which is based on the current master branch with all the gcc 9.3.0 migrations?

**Comment by dalcinl** [comment]
@jan-janssen I'm not sure what I should do exactly. @isuruf @ocefpaf please help.

**Comment by ocefpaf** [comment]
@jan-janssen I recommend instead to close all PRs for petsc 3.13 and move to 3.14 instead. The maintainers are not interested in keeping old versions and they are focused only on a closed loop in the petsc stack, packages outside of that stack that depends on them should move too. See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/906 and https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/899

**Comment by beckermr** [comment]
@ocefpaf This isn't terribly practical advice as moving to 3.14 involves a lot more work for a lot of people. We may want to consider pins for every other version of petsc as we do for boost.

@dalcinl I will make a petsc 3.13 branch on this feedstock and we can backport the gcc930 migration there.

**Comment by ocefpaf** [comment]
IMO it is definitely much easier to move forward with the pinning in this stack. But sure, if you are willing to take care of branching and maintanace of the old version, go for it.

**Comment by beckermr** [comment]
Fair enough. We won't pin again until 3.15 so I think given that the 3.13 migration is almost done, this should be easy enough.

**Comment by isuruf** [comment]
Why 3.15?

**Comment by beckermr** [comment]
we are still on 3.12 and nobody wants to maintain all of the interrelated packages on this stack. Skipping a version to 3.15 decreases the maintenance burden. If someone wants to step up and take over here, I think that would be great!

**Pull request merged**
