### PR TITLE
Rerender and update to version 3.8.0

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by dalcinl** [comment]
@minrk The build failure is related to PT-Scotch. What should I do here?

**Comment by minrk** [comment]
Maybe it needs to be told that ptscotch is in $PREFIX? Or maybe ptscotch also needs a rebuild.

**Comment by dalcinl** [comment]
I ran it locally, and the problem is a missing library in the ptscotch package. I'll work on it tomorrow, most likely yes, we need a rebuild of ptscotch, but I'm planning to also update the branch with all the changes you and me did in the scotch package.

**Comment by dalcinl** [comment]
@minrk I'll wait for the new ptscotch build and backport here your mpiexec fixes.

**Comment by minrk** [comment]
ptscotch builds should be done

**Comment by dalcinl** [comment]
@minrk Hooray! The only nasty bit is the link dependance on system `libc++` on macOS (conda-forge/toolchain-feedstock#13), but at this point, let it be, let it be... Many thanks for all your help and patience.

Please note I've incorporated the tips from Satish Balay about configuring with `--with-{c|cxx|fortran}lib-autodetect=0`. BTW, at some later point I would consider to build the Fortran support. 

Please do the honors and press the merge button.

**Comment by minrk** [comment]
Hooray!

**Pull request merged**
