### PR TITLE
Force build to get mpich 3.3

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by davidbrochart** [comment]
I'm trying to create a recipe for [daetk](https://github.com/conda-forge/staged-recipes/pull/9866) and there are conflicts because the version of mpich that is needed is 3.3, and petsc has been built with 3.2.

**Comment by minrk** [comment]
This isn't bumping mpich to 3.3 because there's at least one dependency that hasn't been bumped yet. I opened https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/301 to start the migration for mpich 3.3 again (the previous migration didn't complete because the previous migrator didn't properly support feedstocks with multiple outputs). Once the dependencies are updated, an automatic PR should show up to do this.

**Comment by davidbrochart** [comment]
@minrk I am opening PRs in petsc's dependencies, but are you saying that they will automatically update? Or rather that petsc will automatically update once its dependencies have changed?

**Comment by minrk** [comment]
@davidbrochart yes, there should be PRs issues automatically in topographical order (they don't work if issued all at once, each PR must be issued only after all its dependencies have been upgraded and published). However, this migrator implementation is new, and apparently doesn't handle everything in the petsc graph correctly, so at least some manual PRs need to be issued.

You can check the migrator's status at https://conda-forge.org/status. It's clearly doing something wrong, since it thinks petsc has been built with 3.3 already.

**Comment by minrk** [comment]
Poking CI since I think dependencies might be all updated now.

**Comment by davidbrochart** [comment]
@minrk Great!

**Comment by minrk** [comment]
Checked the builds, and 3.3 is there. Thanks @davidbrochart !

**Comment by davidbrochart** [comment]
@minrk In https://github.com/conda-forge/staged-recipes/pull/9866 I seems that `petsc` still needs mpich < 3.3:

```
Package mpich conflicts for:
petsc=3.11 -> mpich[version='>=3.2,<3.3.0a0|>=3.2.1,<3.3.0a0']
parmetis=4.0 -> mpich[version='>=3.2,<3.3.0a0|>=3.3,<3.4.0a0']
```

**Comment by davidbrochart** [comment]
The reason was because #69 had been merged before #68 and the build number didn't change between the two PRs, so the build was not uploaded to anaconda.org. Thanks @SylvainCorlay for finding out!

**Pull request merged**
