### PR TITLE
3.21.6 h61510d

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Review by minrk — APPROVED** [review]

**Comment by dalcinl** [comment]
Can we remove the branch after this PR is merged or should we keep it alive?

**Comment by jan-janssen** [comment]
> Can we remove the branch after this PR is merged or should we keep it alive?

We also have separate branches for 3.13.x and 3.10.5 so I think it does not hurt to keep it alive. In addition it helps users to find the exact environment which was used to build the 3.21.6 version.

**Comment by minrk** [comment]
If we don't add the branch to `abi_migration_branches`, nothing is going to happen with the branch (no bot PRs, etc.). So there's no real cost to keeping it, nor really to removing it since the commits are in the history no matter what.

**Pull request merged**
