### PR TITLE
add osx_arm64

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@matthiasdiener nice work getting all the stuff tidied up! 

What else is needed for this one?

**Comment by matthiasdiener** [comment]
@conda-forge-admin restart ci

**Comment by matthiasdiener** [comment]
> @matthiasdiener nice work getting all the stuff tidied up!
> 
> What else is needed for this one?

This still needs https://github.com/conda-forge/mumps-feedstock/pull/75

**Comment by ngam** [comment]
@conda-forge-admin restart ci

**Comment by ngam** [comment]
@conda-forge-linter please rerender

**Comment by matthiasdiener** [comment]
This is ready for review @conda-forge/petsc

**Pull request merged**
