### PR TITLE
3.16.6

### PR DESCRIPTION
**Pull request by dalcinl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dalcinl** [comment]
@minrk @isuruf Any idea why the bot did not pick this version update? Should we change anything in the recipe? Or it is just the bot being unable to handle this particular download URL?

**Comment by dalcinl** [comment]
The arm64 builds with scalar-type=complex on Travis CI are failing for unknown reasons (make is being killed). What should I do?

**Comment by minrk** [comment]
If make is being killed, resource limits are the most common cause. My inclination would be to:

1. skip linux+aarch64+complex with a note,
2. merge, and then 
3. open a new PR reinstating the broken builds to investigate

One option would be to switch the linux_aarch64 builds to azure in `conda-forge.yml`:

```yaml
provider: 
  linux_aarch64: azure
```

IIRC, That may have more resources, but I think it will also be much slower. You might give that one go before removing the builds.

**Comment by minrk** [comment]
Thanks @isuruf!

**Comment by dalcinl** [comment]
I'm confused. According to documentation and [actual code](https://github.com/conda/conda-build/blob/master/conda_build/environ.py#L512), conda-build sets `CPU_COUNT` from `multiprocessing.get_cpu_count()`, exactly as PETSc [does](https://gitlab.com/petsc/petsc/-/blob/main/config/BuildSystem/config/packages/make.py#L201). Is conda-forge tweaking the value of `CPU_COUNT`?

**Comment by isuruf** [comment]
> Is conda-forge tweaking the value of CPU_COUNT?

Yes. `multiprocessing.get_cpu_count()` gets things wrong inside travis containers. It shows 44 cores, but we get only 2 in reality.

**Pull request merged**
