### PR TITLE
Re-render and update version

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by dalcinl** [comment]
@minrk The CI failures are a consequence of the recipe `rm -rf $PREFIX/bin`. Not sure is this should be declared as a bug in conda-build. Maybe re-createing the directory should be enough to workaround the issue. What do you think?

**Comment by minrk** [comment]
Try recreating the directory, and we can follow-up upstream if needed. Is there a good way to prevent these files from being installed in the first place? I'd rather prevent it than undo it in the end, but it wasn't obvious to me how to do it.

**Comment by dalcinl** [comment]
Eventually, I'll review all this again and work with upstream to do things the proper way.

**Comment by dalcinl** [comment]
@minrk I guess this is OK to merge, right?

**Pull request merged**
