### PR TITLE
updated v3.20.0

### PR DESCRIPTION
**Pull request by dalcinl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dalcinl** [comment]
@conda-forge-admin, please rerender

**Comment by dalcinl** [comment]
@isuruf @ocenpaf @minrk Guys, I need help here. After merging this PR, all the built packages failed to upload.

**Comment by minrk** [comment]
re-running in case the failed upload was an intermittent error

**Comment by h-vetinari** [comment]
Please stop randomly smashing buttons. You've managed to restart the _exact same_ job ~20 times which leads to complete resource starvation in conda-forge:

image

**Comment by minrk** [comment]
I hit literally one button to restart the job. You can blame Azure's horrible GitHub integration if it did a bunch of things instead.

**Comment by isuruf** [comment]
@h-vetinari, let's give the maintainers some benefit of the doubt and not come into conclusions. It's a known Azure bug.

**Comment by dalcinl** [comment]
Guys, would it make sense to make a new PR with let say an empty commit, or a bump of the build number?

**Comment by isuruf** [comment]
@dalcinl, the packages should be uploaded now. We cancelled all of the duplicated jobs. (Azure sometimes restarts n builds with n jobs each instead of just 1 build with `n` jobs.)

**Comment by dalcinl** [comment]
Thanks! I'll proceed to get all the other PETSc-related packages in.

**Comment by minrk** [comment]
We can do something like that that next time. This time [worked](https://anaconda.org/conda-forge/petsc/files?version=3.20.0), but it wasted a bunch of resources by starting several duplicate jobs on Azure from a single restart request.

**Comment by h-vetinari** [comment]
> It's a known Azure bug.

I restart bots a lot, and with the following guidelines, it has never happened to me:

* let the job run fully to completion before clicking "re-run", even if that means waiting for the 6h timeout
* press the [button](https://github.com/conda-forge/pandas-feedstock/pull/183#issuecomment-1742297827) once

Having >20 restarts just seemed like an absurdly high number, hence my reaction. I apologise for jumping to conclusions. Still, please try to follow the above guidelines, and don't click more than once.

FWIW, I'm 100% in favour of giving feedstock maintainers more fine-grained control over how azure jobs are restarted/cancelled, but that's a kind of built-in limitation.

**Comment by minrk** [comment]
No worries, sorry for wasting resources!

> let the job run fully to completion before clicking "re-run", even if that means waiting for the 6h timeout

The last run completed 3 days ago

> please try to follow the above guidelines, and don't click more than once.

I will continue to do that, like I did today.

> Having >20 restarts just seemed like an absurdly high number,

I believe it creates one job per matrix entry when this happens, and petsc has 20 variants.

> FWIW, I'm 100% in favour of giving feedstock maintainers more fine-grained control over how azure jobs are restarted/cancelled, but that's a kind of built-in limitation.

Yeah, I _really_ wish I could use the Azure UI directly instead of the GitHub Checks UI which is such a mess. It's weird that the CI service with by far the worst GitHub integration is the one owned by the same company. I don't think I have permission to cancel any jobs once they are launched.

I don't know if azure has github-actions-style concurrency/cancellation to automatically cancel superseded jobs?

**Comment by h-vetinari** [comment]
> I don't know if azure has github-actions-style concurrency/cancellation to automatically cancel superseded jobs?

Generally this works for pushes to the same PR, but not in cases like this one where a wild array of runs gets triggered.



> It's weird that the CI service with by far the worst GitHub integration is the one owned by the same company.

💯

**Pull request merged**
