### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jakirkham** [comment]
Any chance we can get this merged @conda-forge/petsc ? This is needed for us to move to conda-build 2. Thanks.

**Comment by jjhelmus** [comment]
Thanks all!

**Comment by jjhelmus** [comment]
Something is wonky with the Linux build here.  The `upload_or_check_non_existence /recipe_root conda-forge --channel=main || exit 1` line of the `run_docker_build.sh` script never gets runs and therefore the package never gets uploaded.  There is a note in the `run_test.sh` script which metioned this.  

Unfortunately without a long prefix Linux build of `petsc` a long prefix build of `slepc` cannot be made.  See conda-forge/slepc-feedstock#1

**Comment by minrk** [comment]
Hm, I had an issue with missing uploads a while ago, which prompted https://github.com/conda-forge/conda-smithy/pull/337. I'm not sure how updating conda-build would reintroduce that, though.

**Comment by jakirkham** [comment]
In the past, this has been related to running the tests somehow. 😕 Commenting them or guarding them on Linux may be sufficient to get the upload to work.

That being said, I agree completely with @minrk that the right solution is to fix how we are doing the build/upload on CircleCI. I strongly suspect that having a proper TTY instead of all this IO redirection avoids a lot of weird flaky issues that do result in things like failed uploads amongst other odd problems.

**Comment by jakirkham** [comment]
FYI we are switching to `conda-build` 2 after discussion in our meeting today. So we should work out how to fix this ASAP. My recommendation would be to add a branch to the feedstock and start playing with changes in that branch directly once we have something that works we will be able to see that from the CI result showing the upload.

**Pull request merged**
