### PR TITLE
not needed anymore

### PR DESCRIPTION
**Pull request by MarDiehl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

constrained on hypre version not needed anymore

### CODE REVIEW

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by dalcinl** [comment]
@MarDiehl I think we should add 8c78285434e5d71cc2b9fb7381d9cf2cb6fd3130 on top of #126 and close this one. I can do it quickly. Do you agree?

**Comment by MarDiehl** [comment]
> @MarDiehl I think we should add [8c78285](https://github.com/conda-forge/petsc-feedstock/commit/8c78285434e5d71cc2b9fb7381d9cf2cb6fd3130) on top of #126 and close this one. I can do it quickly. Do you agree?

fine from my side.

**Comment by dalcinl** [comment]
Closed in favor of #126.

**Pull request closed without merging**
