### PR TITLE
build with mumps, hypre, metis, parmetis

### LINKED ISSUE #12: Add MUMPS
Adding MUMPS would provide a parallel direct solver. 

MUMPS is packaged at https://github.com/conda-forge/mumps-feedstock, but will probably need some work. The MUMPS conda package depends on scotch rather than pt-scotch, which may mean that it won't work in parallel.

There is also an issue with scalpack to sort out.

### PR DESCRIPTION
**Pull request by minrk**
using new mumps-mpi package

updates openblas pin syntax for conda-forge pin bot find

closes #12 and #15

### CODE REVIEW

**Comment by dalcinl** [comment]
@minrk May I ask why you need the configure patch?

**Comment by minrk** [comment]
The patch was required to find metis, at least on mac. However, now that I remember the conflicts with scotch's metis.h, I suspect that it may have been another symptom of the same thing. I'll remove the patch and see if it still works.

**Comment by minrk** [comment]
Looks like it was related to that conflict. Patch removed.

**Comment by minrk** [comment]
@dalcinl is it okay to merge this one?

**Comment by dalcinl** [comment]
Yes, sure! Go ahead and merge.

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
